name: Daily Autonomous Site Builder

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:      # Manual trigger via GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run autonomous site builder script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_MODEL: bigcode/starcoder2-3b
        run: |
          python script/generate.py

      - name: Ensure dashboard/sites.json exists (optional)
        run: |
          mkdir -p dashboard
          touch dashboard/sites.json

      - name: Upload dashboard (optional backup step)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dashboard-backup
          path: dashboard/sites.json
